listener {
    timeout = 290      # seconds of inactivity
    on-timeout = notify-send "SCREEN TURNING OFF" 
    on-resume = notify-send "SCREEN ON RESUME" 
}
listener {
    timeout = 300      # seconds of inactivity
    on-timeout =  hyprctl dispatch dpms off
    on-resume =  hyprctl dispatch dpms on
}

listener {
    timeout = 1800      # seconds of inactivity
    on-timeout =  systemctl suspend
}

